/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* ADC_IRQ */
#define ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ__INTC_NUMBER 138u
#define ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ_INTC_NUMBER 138u

/* MCWDT_isr */
#define MCWDT_isr__INTC_CORTEXM4_ASSIGNED 1
#define MCWDT_isr__INTC_CORTEXM4_PRIORITY 7u
#define MCWDT_isr__INTC_NUMBER 19u
#define MCWDT_isr_INTC_CORTEXM4_ASSIGNED 1
#define MCWDT_isr_INTC_CORTEXM4_PRIORITY 7u
#define MCWDT_isr_INTC_NUMBER 19u

/* I2C_SCB_IRQ */
#define I2C_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_SCB_IRQ__INTC_NUMBER 44u
#define I2C_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_SCB_IRQ_INTC_NUMBER 44u

/* UART_SCB_IRQ */
#define UART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ__INTC_NUMBER 46u
#define UART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ_INTC_NUMBER 46u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM4_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM4_PRIORITY 7u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM4_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM4_PRIORITY 7u
#define BLE_bless_isr_INTC_NUMBER 24u

/* RTC_1_RTC_IRQ */
#define RTC_1_RTC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define RTC_1_RTC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define RTC_1_RTC_IRQ__INTC_NUMBER 21u
#define RTC_1_RTC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define RTC_1_RTC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define RTC_1_RTC_IRQ_INTC_NUMBER 21u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
