/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.3 Early Access
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_1 */
#define Pin_1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_0_INBUF_ENABLED 0u
#define Pin_1_0_INIT_DRIVESTATE 1u
#define Pin_1_0_INIT_MUXSEL 0u
#define Pin_1_0_INPUT_SYNC 2u
#define Pin_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_0_NUM 3u
#define Pin_1_0_PORT GPIO_PRT10
#define Pin_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_INBUF_ENABLED 0u
#define Pin_1_INIT_DRIVESTATE 1u
#define Pin_1_INIT_MUXSEL 0u
#define Pin_1_INPUT_SYNC 2u
#define Pin_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_NUM 3u
#define Pin_1_PORT GPIO_PRT10
#define Pin_1_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_2 */
#define Pin_2_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_2_0_INBUF_ENABLED 0u
#define Pin_2_0_INIT_DRIVESTATE 1u
#define Pin_2_0_INIT_MUXSEL 0u
#define Pin_2_0_INPUT_SYNC 2u
#define Pin_2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_2_0_NUM 0u
#define Pin_2_0_PORT GPIO_PRT10
#define Pin_2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_2_INBUF_ENABLED 0u
#define Pin_2_INIT_DRIVESTATE 1u
#define Pin_2_INIT_MUXSEL 0u
#define Pin_2_INPUT_SYNC 2u
#define Pin_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_2_NUM 0u
#define Pin_2_PORT GPIO_PRT10
#define Pin_2_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_3 */
#define Pin_3_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_3_0_INBUF_ENABLED 0u
#define Pin_3_0_INIT_DRIVESTATE 1u
#define Pin_3_0_INIT_MUXSEL 0u
#define Pin_3_0_INPUT_SYNC 2u
#define Pin_3_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_3_0_NUM 1u
#define Pin_3_0_PORT GPIO_PRT10
#define Pin_3_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_3_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_3_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_3_INBUF_ENABLED 0u
#define Pin_3_INIT_DRIVESTATE 1u
#define Pin_3_INIT_MUXSEL 0u
#define Pin_3_INPUT_SYNC 2u
#define Pin_3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_3_NUM 1u
#define Pin_3_PORT GPIO_PRT10
#define Pin_3_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_scl */
#define I2C_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_scl_0_INBUF_ENABLED 1u
#define I2C_scl_0_INIT_DRIVESTATE 1u
#define I2C_scl_0_INIT_MUXSEL 19u
#define I2C_scl_0_INPUT_SYNC 2u
#define I2C_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_scl_0_NUM 0u
#define I2C_scl_0_PORT GPIO_PRT6
#define I2C_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_scl_INBUF_ENABLED 1u
#define I2C_scl_INIT_DRIVESTATE 1u
#define I2C_scl_INIT_MUXSEL 19u
#define I2C_scl_INPUT_SYNC 2u
#define I2C_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_scl_NUM 0u
#define I2C_scl_PORT GPIO_PRT6
#define I2C_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_sda */
#define I2C_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_sda_0_INBUF_ENABLED 1u
#define I2C_sda_0_INIT_DRIVESTATE 1u
#define I2C_sda_0_INIT_MUXSEL 19u
#define I2C_sda_0_INPUT_SYNC 2u
#define I2C_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_sda_0_NUM 1u
#define I2C_sda_0_PORT GPIO_PRT6
#define I2C_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_sda_INBUF_ENABLED 1u
#define I2C_sda_INIT_DRIVESTATE 1u
#define I2C_sda_INIT_MUXSEL 19u
#define I2C_sda_INPUT_SYNC 2u
#define I2C_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_sda_NUM 1u
#define I2C_sda_PORT GPIO_PRT6
#define I2C_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Uart_RX */
#define Uart_RX_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Uart_RX_0_INBUF_ENABLED 1u
#define Uart_RX_0_INIT_DRIVESTATE 0u
#define Uart_RX_0_INIT_MUXSEL 18u
#define Uart_RX_0_INPUT_SYNC 2u
#define Uart_RX_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_RX_0_NUM 0u
#define Uart_RX_0_PORT GPIO_PRT5
#define Uart_RX_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_RX_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Uart_RX_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Uart_RX_INBUF_ENABLED 1u
#define Uart_RX_INIT_DRIVESTATE 0u
#define Uart_RX_INIT_MUXSEL 18u
#define Uart_RX_INPUT_SYNC 2u
#define Uart_RX_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_RX_NUM 0u
#define Uart_RX_PORT GPIO_PRT5
#define Uart_RX_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_RX_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Uart_TX */
#define Uart_TX_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Uart_TX_0_INBUF_ENABLED 0u
#define Uart_TX_0_INIT_DRIVESTATE 1u
#define Uart_TX_0_INIT_MUXSEL 18u
#define Uart_TX_0_INPUT_SYNC 2u
#define Uart_TX_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_TX_0_NUM 1u
#define Uart_TX_0_PORT GPIO_PRT5
#define Uart_TX_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_TX_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Uart_TX_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Uart_TX_INBUF_ENABLED 0u
#define Uart_TX_INIT_DRIVESTATE 1u
#define Uart_TX_INIT_MUXSEL 18u
#define Uart_TX_INPUT_SYNC 2u
#define Uart_TX_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_TX_NUM 1u
#define Uart_TX_PORT GPIO_PRT5
#define Uart_TX_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_TX_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Work_led */
#define Work_led_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Work_led_0_INBUF_ENABLED 0u
#define Work_led_0_INIT_DRIVESTATE 1u
#define Work_led_0_INIT_MUXSEL 0u
#define Work_led_0_INPUT_SYNC 2u
#define Work_led_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Work_led_0_NUM 4u
#define Work_led_0_PORT GPIO_PRT7
#define Work_led_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Work_led_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Work_led_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Work_led_INBUF_ENABLED 0u
#define Work_led_INIT_DRIVESTATE 1u
#define Work_led_INIT_MUXSEL 0u
#define Work_led_INPUT_SYNC 2u
#define Work_led_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Work_led_NUM 4u
#define Work_led_PORT GPIO_PRT7
#define Work_led_SLEWRATE CY_GPIO_SLEW_FAST
#define Work_led_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Charge_led */
#define Charge_led_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Charge_led_0_INBUF_ENABLED 0u
#define Charge_led_0_INIT_DRIVESTATE 1u
#define Charge_led_0_INIT_MUXSEL 3u
#define Charge_led_0_INPUT_SYNC 2u
#define Charge_led_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Charge_led_0_NUM 2u
#define Charge_led_0_PORT GPIO_PRT7
#define Charge_led_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Charge_led_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Charge_led_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Charge_led_INBUF_ENABLED 0u
#define Charge_led_INIT_DRIVESTATE 1u
#define Charge_led_INIT_MUXSEL 3u
#define Charge_led_INPUT_SYNC 2u
#define Charge_led_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Charge_led_NUM 2u
#define Charge_led_PORT GPIO_PRT7
#define Charge_led_SLEWRATE CY_GPIO_SLEW_FAST
#define Charge_led_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Connect_led */
#define Connect_led_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Connect_led_0_INBUF_ENABLED 0u
#define Connect_led_0_INIT_DRIVESTATE 1u
#define Connect_led_0_INIT_MUXSEL 0u
#define Connect_led_0_INPUT_SYNC 2u
#define Connect_led_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Connect_led_0_NUM 3u
#define Connect_led_0_PORT GPIO_PRT7
#define Connect_led_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Connect_led_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Connect_led_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Connect_led_INBUF_ENABLED 0u
#define Connect_led_INIT_DRIVESTATE 1u
#define Connect_led_INIT_MUXSEL 0u
#define Connect_led_INPUT_SYNC 2u
#define Connect_led_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Connect_led_NUM 3u
#define Connect_led_PORT GPIO_PRT7
#define Connect_led_SLEWRATE CY_GPIO_SLEW_FAST
#define Connect_led_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* MAX30102_int */
#define MAX30102_int_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define MAX30102_int_0_INBUF_ENABLED 1u
#define MAX30102_int_0_INIT_DRIVESTATE 0u
#define MAX30102_int_0_INIT_MUXSEL 0u
#define MAX30102_int_0_INPUT_SYNC 2u
#define MAX30102_int_0_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define MAX30102_int_0_NUM 3u
#define MAX30102_int_0_PORT GPIO_PRT6
#define MAX30102_int_0_SLEWRATE CY_GPIO_SLEW_FAST
#define MAX30102_int_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define MAX30102_int_DRIVEMODE CY_GPIO_DM_HIGHZ
#define MAX30102_int_INBUF_ENABLED 1u
#define MAX30102_int_INIT_DRIVESTATE 0u
#define MAX30102_int_INIT_MUXSEL 0u
#define MAX30102_int_INPUT_SYNC 2u
#define MAX30102_int_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define MAX30102_int_NUM 3u
#define MAX30102_int_PORT GPIO_PRT6
#define MAX30102_int_SLEWRATE CY_GPIO_SLEW_FAST
#define MAX30102_int_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Charge_status */
#define Charge_status_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Charge_status_0_INBUF_ENABLED 1u
#define Charge_status_0_INIT_DRIVESTATE 0u
#define Charge_status_0_INIT_MUXSEL 0u
#define Charge_status_0_INPUT_SYNC 2u
#define Charge_status_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Charge_status_0_NUM 6u
#define Charge_status_0_PORT GPIO_PRT5
#define Charge_status_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Charge_status_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Charge_status_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Charge_status_INBUF_ENABLED 1u
#define Charge_status_INIT_DRIVESTATE 0u
#define Charge_status_INIT_MUXSEL 0u
#define Charge_status_INPUT_SYNC 2u
#define Charge_status_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Charge_status_NUM 6u
#define Charge_status_PORT GPIO_PRT5
#define Charge_status_SLEWRATE CY_GPIO_SLEW_FAST
#define Charge_status_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* MAX30102_enable */
#define MAX30102_enable_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define MAX30102_enable_0_INBUF_ENABLED 0u
#define MAX30102_enable_0_INIT_DRIVESTATE 1u
#define MAX30102_enable_0_INIT_MUXSEL 0u
#define MAX30102_enable_0_INPUT_SYNC 2u
#define MAX30102_enable_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define MAX30102_enable_0_NUM 5u
#define MAX30102_enable_0_PORT GPIO_PRT5
#define MAX30102_enable_0_SLEWRATE CY_GPIO_SLEW_FAST
#define MAX30102_enable_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define MAX30102_enable_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define MAX30102_enable_INBUF_ENABLED 0u
#define MAX30102_enable_INIT_DRIVESTATE 1u
#define MAX30102_enable_INIT_MUXSEL 0u
#define MAX30102_enable_INPUT_SYNC 2u
#define MAX30102_enable_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define MAX30102_enable_NUM 5u
#define MAX30102_enable_PORT GPIO_PRT5
#define MAX30102_enable_SLEWRATE CY_GPIO_SLEW_FAST
#define MAX30102_enable_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
